audit_header: false
title: "Cheyenne's Best Real Estate Training"
description: JP Fluellen, a top Real Estate Agent in Cheyenne, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
client:
  name: JP Fluellen
  title:
  license_number:
  about_markdown: |
    JP Fluellen, an Army Veteran, has lived in Cheyenne since 2007 and grew up in Grand Forks, North Dakota. He served in the Army National Guard from 1994-2007 with one tour in Iraq. He is a married father of 4 wonderful children. JP became a licensed real estate agent in 2010 after being a real estate investor for 2 years. He's been a top real estate agent at Coldwell Banker The Property Exchange and has recently started the Titan Real Estate Team at eXp Realty. He has sold over 400 houses in the Cheyenne Market and also wrote a book called the Real Estate Brain to be released in 2019. JP started his own podcast in 2011 called The Wire and a Facebook live podcast called Success Agents at the beginning of 2019. He was in Cheyenne's premier bands "6 Grand" for 7 years. JP Fluellen also uses the latest Internet marketing tools including video, 3D, and AI.
  market: Cheyenne
  brand: Titan Real Estate Team
  brokerage:
  address: 109 E. 17th St. Cheyenne WY 82001
  phone: 307-772-1184
  phone_type:
  phone2:
  phone2_type:
  email: james.fluellen@gmail.com
  url:

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Titan Real Estate Team can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Cheyenne Real Estate Podcast with JP Fluellen'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Cheyenne Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Titan Real Estate Team - your professional Cheyenne Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Cheyenne, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'JP Fluellen'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Cheyenne Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#f4801d'
  theme_color: '#010330'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
